name: Build Multi-Platform Binary

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-desktop:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        python-version: [3.10]

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Setup Python
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install PyInstaller
      run: |
        python -m pip install --upgrade pip
        pip install pyinstaller

    - name: Create directories
      run: |
        python -c "import os; os.makedirs('dist', exist_ok=True); os.makedirs('spec', exist_ok=True)"

    - name: Build Desktop Binary
      run: |
        pyinstaller --onefile --specpath spec --name grok_farewell grok_farewell.py

    - name: Generate checksum
      run: |
        import hashlib
        import sys
        import os

        binary_name = "grok_farewell"
        if sys.platform.startswith("win"):
            binary_name += ".exe"
        binary_path = os.path.join("dist", binary_name)

        with open(binary_path, "rb") as f:
            checksum = hashlib.sha256(f.read()).hexdigest()

        with open("dist/CHECKSUM.txt", "w") as out:
            out.write(checksum + "\n")

    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: desktop-binaries-${{ matrix.os }}
        path: |
          dist/*
