name: Build Multi-Platform Python Binary

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build-desktop:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        python-version: [3.11]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pyinstaller

      - name: Prepare build directories
        shell: bash
        run: |
          if [[ "${{ runner.os }}" == "Windows" ]]; then
            powershell -Command "New-Item -ItemType Directory -Force -Path dist,spec"
          else
            mkdir -p dist spec
          fi

      - name: Build executable
        shell: bash
        run: |
          if [[ "${{ runner.os }}" == "Windows" ]]; then
            pyinstaller --onefile main.py --distpath dist --workpath spec
          else
            pyinstaller --onefile main.py --distpath dist --workpath spec
          fi

      - name: Generate checksum
        shell: bash
        run: |
          if [[ "${{ runner.os }}" == "Windows" ]]; then
            python -c "import hashlib, os; f=open(os.path.join('dist','main.exe'),'rb'); print(hashlib.sha256(f.read()).hexdigest())" > dist/CHECKSUM.txt
          else
            python -c "import hashlib; f=open('./dist/main','rb'); print(hashlib.sha256(f.read()).hexdigest())" > dist/CHECKSUM.txt

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: desktop-binary-${{ matrix.os }}
          path: dist/
