---
name: Build (Android APK via Buildozer)

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-android:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python 3.10
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            zip unzip openjdk-17-jdk python3-pip libffi-dev \
            libssl-dev zlib1g-dev libjpeg-dev libpng-dev \
            libfreetype6-dev liblzma-dev libtiff5-dev git wget

      - name: Install Buildozer
        run: |
          python3 -m pip install --upgrade pip setuptools wheel
          pip install buildozer cython virtualenv

      - name: Prepare Android SDK & NDK
        env:
          ANDROID_HOME: ${{ github.workspace }}/.buildozer/android/platform/android-sdk
        run: |
          mkdir -p $ANDROID_HOME/cmdline-tools
          wget -q https://dl.google.com/android/repository/commandlinetools-linux-11076708_latest.zip -O cmdline-tools.zip
          unzip -q cmdline-tools.zip -d $ANDROID_HOME/cmdline-tools
          mv $ANDROID_HOME/cmdline-tools/cmdline-tools $ANDROID_HOME/cmdline-tools/latest
          yes | $ANDROID_HOME/cmdline-tools/latest/bin/sdkmanager --sdk_root=$ANDROID_HOME "platform-tools" "build-tools;34.0.0" "platforms;android-34" "ndk;26.1.10909125" >/dev/null

          # Automatically accept all SDK licenses
          yes | $ANDROID_HOME/cmdline-tools/latest/bin/sdkmanager --licenses --sdk_root=$ANDROID_HOME

      - name: Build the APK with Buildozer
        env:
          ANDROID_HOME: ${{ github.workspace }}/.buildozer/android/platform/android-sdk
        run: |
          rm -rf .buildozer
          buildozer -v android debug

      - name: Upload built APK
        uses: actions/upload-artifact@v4
        with:
          name: android-apk
          path: bin/*.apk
