name: Build (Android APK via Buildozer)

on:
  push:
    branches: [ main ]

jobs:
  build-android:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y python3-pip zip unzip openjdk-17-jdk libffi-dev libssl-dev zlib1g-dev

      - name: Install Buildozer
        run: |
          pip install --upgrade pip
          pip install buildozer cython virtualenv

      - name: Prepare Android SDK/NDK
        run: |
          mkdir -p $HOME/.buildozer/android/platform
          wget https://dl.google.com/android/repository/commandlinetools-linux-11076708_latest.zip -O cmdline-tools.zip
          unzip cmdline-tools.zip -d $HOME/.buildozer/android/cmdline-tools
          yes | $HOME/.buildozer/android/cmdline-tools/cmdline-tools/bin/sdkmanager --sdk_root=$HOME/.buildozer/android "platform-tools" "build-tools;34.0.0" "platforms;android-34" "ndk;26.1.10909125"

      - name: Build APK
        run: |
          buildozer -v android debug

      - uses: actions/upload-artifact@v4
        with:
          name: android-apk
          path: bin/*.apk
