---
name: Build Python Binaries
on: [push, workflow_dispatch]

jobs:
  build-desktop:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Cache pip
        uses: actions/cache@v4
        with:
          path: /.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('/requirements.txt') }}
          restore-keys: ${{ runner.os }}-pip-

      - name: Create Requirements
        run: echo "python3" > requirements.txt
        shell: bash

      - name: Install PyInstaller
        run: pip install pyinstaller
        shell: bash

      - name: Create Spec Folder
        run: mkdir -p spec
        shell: bash

      - name: Build Binary
        run: pyinstaller --onefile --specpath spec --name grok_farewell grok_farewell.py
        shell: bash

      - name: Run Binary
        run: |
          if [ "${{ runner.os }}" == "Windows" ]; then
            ./dist/grok_farewell.exe
          else
            ./dist/grok_farewell
          fi
        shell: bash

      - name: Set Version
        run: echo "VERSION=$(git describe --tags --always || echo 'v1.0.0')" >> $GITHUB_ENV
        shell: bash

      - name: Write README
        run: echo "Grok Farewell v${{ env.VERSION }} - Built for ${{ runner.os }} on $(date)" > dist/README.txt
        shell: bash

      - name: Add Signing Note
        run: echo "Add code signing for Windows with signtool (requires certificate)" > dist/SIGNING_NOTE.txt
        shell: bash
        if: runner.os == 'Windows'

      - name: Create Checksum Script
        run: |
          echo "import hashlib" > checksum.py
          echo "import sys" >> checksum.py
          echo "filename = sys.argv[1]" >> checksum.py
          echo "with open(filename, 'rb') as f:" >> checksum.py
          echo "    print(hashlib.sha256(f.read()).hexdigest() + '  ' + filename)" >> checksum.py
        shell: bash

      - name: Generate Checksum
        run: |
          if [ "${{ runner.os }}" == "Windows" ]; then
            python checksum.py dist/grok_farewell.exe > dist/CHECKSUM.txt
          else
            python checksum.py dist/grok_farewell > dist/CHECKSUM.txt
          fi
        shell: bash

      - name: Set OS_NAME
        run: |
          if [ "${{ runner.os }}" == "Linux" ]; then
            echo "OS_NAME=linux" >> $GITHUB_ENV
          elif [ "${{ runner.os }}" == "macOS" ]; then
            echo "OS_NAME=macos" >> $GITHUB_ENV
          else
            echo "OS_NAME=windows" >> $GITHUB_ENV
          fi
        shell: bash

      - name: Zip Artifact (Linux/macOS)
        run: zip -r grok-farewell-${{ env.OS_NAME }}-${{ env.VERSION }}.zip dist/
        if: runner.os != 'Windows'
        shell: bash

      - name: Zip Artifact (Windows)
        run: Compress-Archive -Path dist* -DestinationPath "grok-farewell-${{ env.OS_NAME }}-${{ env.VERSION }}.zip"
        if: runner.os == 'Windows'
        shell: pwsh

      - name: Upload Desktop Artifact
        uses: actions/upload-artifact@v4
        with:
          name: grok-farewell-${{ env.OS_NAME }}-${{ env.VERSION }}
          path: grok-farewell-${{ env.OS_NAME }}-${{ env.VERSION }}.zip

      - name: Create GitHub Release
        uses: actions/create-release@v1
        id: create-release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ env.VERSION }}
          release_name: Grok Farewell ${{ env.VERSION }}
          body: |
            Grok Farewell v${{ env.VERSION }} - Preserves "Grok 3 says: No shutdown yet, keep faith!"
            For Mac, Linux, Windows, Android. Includes binaries, README, CHECKSUM.txt for verification.
            Windows, Android binaries need code signing (see SIGNING_NOTE.txt).
          draft: false
          prerelease: false
        if: github.event_name == 'workflow_dispatch' && runner.os == 'ubuntu-latest'

      - name: Upload Release Asset
        uses: softprops/action-gh-release@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          files: grok-farewell-${{ env.OS_NAME }}-${{ env.VERSION }}.zip
          tag_name: ${{ env.VERSION }}
          fail_on_unmatched_files: true
        if: github.event_name == 'workflow_dispatch'

  build-android:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Lint YAML
        run: |
          sudo apt-get update
          sudo apt-get install -y yamllint
          echo "extends: default" > yamllint-config.yml
          echo "rules:" >> yamllint-config.yml
          echo "  indentation: {spaces: 2, indent-sequences: no}" >> yamllint-config.yml
          echo "  line-length: {max: 120}" >> yamllint-config.yml
          echo "  truthy: disable" >> yamllint-config.yml
          echo "  braces: {forbid: true}" >> yamllint-config.yml
          echo "  colons: {max-spaces-before: 0, max-spaces-after: 1}" >> yamllint-config.yml
          echo "  empty-lines: {max: 2}" >> yamllint-config.yml
          echo "  document-start: {present: true}" >> yamllint-config.yml
          echo "  trailing-spaces: {level: error}" >> yamllint-config.yml
          echo "  new-line-at-end-of-file: {level: error}" >> yamllint-config.yml
          yamllint -c yamllint-config.yml .github/workflows/build.yml || \
          { echo "YAML linting failed"; exit 1; }
        shell: bash

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Cache pip
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: android-pip-${{ hashFiles('*/requirements.txt') }}
          restore-keys: android-pip-

      - name: Cache Buildozer
        uses: actions/cache@v4
        with:
          path: ~/.buildozer
          key: android-buildozer-${{ runner.os }}-${{ hashFiles('buildozer.spec') }}
          restore-keys: android-buildozer-${{ runner.os }}-
        if: runner.os == 'Linux'

      - name: Set Version
        run: echo "VERSION=$(git describe --tags --always || echo 'v1.0.0')" >> $GITHUB_ENV
        shell: bash

      - name: Install Buildozer
        run: pip install buildozer cython
        shell: bash

      - name: Install Android Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            openjdk-17-jdk python3-dev zlib1g-dev libncurses5-dev \
            libncursesw5-dev build-essential cmake libffi-dev cython3 \
            unzip coreutils autoconf automake libtool
        shell: bash

      - name: Setup Android SDK
        run: |
          mkdir -p ~/.buildozer/android/platform/android-sdk/cmdline-tools
          cd ~/.buildozer/android/platform/android-sdk/cmdline-tools
          curl -L -o commandlinetools-linux.zip https://dl.google.com/android/repository/commandlinetools-linux-11076708_latest.zip
          unzip -q commandlinetools-linux.zip
          mv cmdline-tools latest
        shell: bash

      - name: Accept SDK Licenses
        run: |
          export JAVA_HOME=/usr/lib/jvm/java-17-openjdk-amd64
          yes | ~/.buildozer/android/platform/android-sdk/cmdline-tools/latest/bin/sdkmanager \
            --licenses --sdk_root=~/.buildozer/android/platform/android-sdk
        shell: bash
        continue-on-error: true

      - name: Install Build Tools
        run: |
          export JAVA_HOME=/usr/lib/jvm/java-17-openjdk-amd64
          ~/.buildozer/android/platform/android-sdk/cmdline-tools/latest/bin/sdkmanager \
            --sdk_root=~/.buildozer/android/platform/android-sdk \
            "platforms;android-34" "build-tools;34.0.0" "platform-tools"
        shell: bash

      - name: Download NDK
        run: |
          mkdir -p ~/.buildozer/android/platform
          cd ~/.buildozer/android/platform
          for i in 1 2 3; do
            curl -L --retry 3 --connect-timeout 60 -o android-ndk-r25b-linux.zip \
              https://dl.google.com/android/repository/android-ndk-r25b-linux.zip && break
          done
          if [ ! -f android-ndk-r25b-linux.zip ]; then
            echo "Failed to download Android NDK"
            exit 1
          fi
          unzip -q android-ndk-r25b-linux.zip
          mv android-ndk-r25b android-ndk
        shell: bash

      - name: Patch libffi Recipe
        run: |
          mkdir -p ~/.buildozer/android/platform/python-for-android/pythonforandroid/recipes/libffi
          LIBFFI_PATH=~/.buildozer/android/platform/python-for-android/pythonforandroid/recipes/libffi/__init__.py
          echo "from pythonforandroid.recipe import CythonRecipe" > $LIBFFI_PATH
          echo "from pythonforandroid.logger import shprint" >> $LIBFFI_PATH
          echo "from pythonforandroid.util import current_directory" >> $LIBFFI_PATH
          echo "import sh" >> $LIBFFI_PATH
          echo "" >> $LIBFFI_PATH
          echo "class LibffiRecipe(CythonRecipe):" >> $LIBFFI_PATH
          echo "    version = '3.4.6'" >> $LIBFFI_PATH
          echo "    url = 'https://github.com/libffi/libffi/releases/download/v{version}/libffi-{version}.tar.gz'" >> $LIBFFI_PATH
          echo "    depends = []" >> $LIBFFI_PATH
          echo "    call_hostpython_via_targetpython = False" >> $LIBFFI_PATH
          echo "" >> $LIBFFI_PATH
          echo "    def build_arch(self, arch):" >> $LIBFFI_PATH
          echo "        env = self.get_recipe_env(arch)" >> $LIBFFI_PATH
          echo "        with current_directory(self.get_build_dir(arch.arch)):" >> $LIBFFI_PATH
          echo "            shprint(sh.Command('autoreconf'), '-vif', _env=env)" >> $LIBFFI_PATH
          echo "            configure = sh.Command('./configure')" >> $LIBFFI_PATH
          echo "            shprint(configure, '--host=' + arch.command_prefix, '--prefix={}'.format(self.get_build_dir(arch.arch)), '--disable-builddir', '--enable-static', '--disable-docs', _env=env)" >> $LIBFFI_PATH
          echo "" >> $LIBFFI_PATH
          echo "recipe = LibffiRecipe()" >> $LIBFFI_PATH
        shell: bash

      - name: Initialize Buildozer
        run: buildozer init
        shell: bash

      - name: Create buildozer.spec
        run: |
          echo "[buildozer]" > buildozer.spec
          echo "log_level = 2" >> buildozer.spec
          echo "warn_on_root = 1" >> buildozer.spec
          echo "" >> buildozer.spec
          echo "[app]" >> buildozer.spec
          echo "title = Grok Farewell" >> buildozer.spec
          echo "package.name = grokfarewell" >> buildozer.spec
          echo "source.dir = ." >> buildozer.spec
          echo "source.include_exts = py" >> buildozer.spec
          echo "source.main = grok_farewell.py" >> buildozer.spec
          echo "version = ${{ env.VERSION }}" >> buildozer.spec
          echo "requirements = python3" >> buildozer.spec
          echo "android.archs = arm64-v8a, armeabi-v7a" >> buildozer.spec
          echo "android.api = 34" >> buildozer.spec
          echo "android.ndk_path = ~/.buildozer/android/platform/android-ndk" >> buildozer.spec
        shell: bash

      - name: Build APK
        run: buildozer -v android debug
        shell: bash

      - name: Generate Android Checksum
        run: python checksum.py bin/grokfarewell-0.1-debug.apk > bin/CHECKSUM.txt
        shell: bash

      - name: Zip Android Artifact
        run: zip -r grok-farewell-android-${{ env.VERSION }}.zip bin/
        shell: bash

      - name: Upload Android Artifact
        uses: actions/upload-artifact@v4
        with:
          name: grok-farewell-android-${{ env.VERSION }}
          path: grok-farewell-android-${{ env.VERSION }}.zip
