name: Build Python Binaries
on:
  push:
  workflow_dispatch:

jobs:
  build-desktop:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install PyInstaller
        run: pip install pyinstaller

      - name: Build Desktop Binary
        run: |
          mkdir -p dist spec
          pyinstaller --onefile --specpath spec --name grok_farewell grok_farewell.py

      - name: Create Checksum
        run: |
          python - <<PYTHON
import hashlib
import os

filename = "./dist/grok_farewell"
if os.name == "nt":
    filename += ".exe"

with open(filename, "rb") as f:
    checksum = hashlib.sha256(f.read()).hexdigest()

with open("dist/CHECKSUM.txt", "w") as out:
    out.write(checksum + "  " + filename + "\n")
PYTHON

      - name: Set OS Name
        run: |
          if [ "${{ runner.os }}" == "Linux" ]; then
            echo "OS_NAME=linux" >> $GITHUB_ENV
          elif [ "${{ runner.os }}" == "macOS" ]; then
            echo "OS_NAME=macos" >> $GITHUB_ENV
          else
            echo "OS_NAME=windows" >> $GITHUB_ENV
          fi

      - name: Zip Artifact
        run: |
          if [ "${{ runner.os }}" == "Windows" ]; then
            powershell -Command "Compress-Archive -Path dist/* -DestinationPath 'grok-farewell-${{ env.OS_NAME }}.zip'"
          else
            zip -r "grok-farewell-${{ env.OS_NAME }}.zip" dist/
          fi

      - uses: actions/upload-artifact@v4
        with:
          name: grok-farewell-${{ env.OS_NAME }}
          path: grok-farewell-${{ env.OS_NAME }}.zip
